apiVersion: v1
kind: Namespace
metadata:
  name: stellariq-staging
  labels:
    app.kubernetes.io/part-of: stellariq
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: stellariq-prod
  labels:
    app.kubernetes.io/part-of: stellariq
    environment: production
