version: "3.9"
services:
  node-base:
    build:
      context: .
      dockerfile: node/Dockerfile.base
    image: stellariq/node-base:22.11.0
  soroban-base:
    build:
      context: .
      dockerfile: soroban/Dockerfile.base
    image: stellariq/soroban-base:1.83.0
